// Code generated by decoder_cursor_gen.go; DO NOT EDIT.
//go:build go1.27

package simdjson

import (
	"math/bits"
	"reflect"
	"strconv"
	"unsafe"

	"github.com/thesyncim/simdjson/internal/byteview"
)

// Bool decodes directly into any defined boolean type.
func (c *decoderCursor) Bool[T boolValue](dst *T) error {
	i := c.i
	if i < len(c.src) {
		switch c.src[i] {
		case 't':
			if literalTrueAt(c.src, i) {
				*dst = true
				c.i = i + 4
				return nil
			}
		case 'f':
			if literalFalseTailAt(c.src, i) {
				*dst = false
				c.i = i + 5
				return nil
			}
		}
	}
	return c.boolSlow(dst)
}

//go:noinline
func (c *decoderCursor) boolSlow[T boolValue](dst *T) error {
	i := c.i
	if i >= len(c.src) {
		return c.genericExpected[T]("boolean")
	}
	if c.src[i] == 'n' {
		if !literalNullAt(c.src, i) {
			return c.err(i, "invalid literal")
		}
		if c.flags&decoderReplace != 0 {
			*dst = false
		}
		c.i = i + 4
		return nil
	}
	switch c.src[i] {
	case 't':
		if !literalTrueAt(c.src, i) {
			return c.err(i, "invalid literal")
		}
		*dst = true
		c.i = i + 4
		return nil
	case 'f':
		if !literalFalseTailAt(c.src, i) {
			return c.err(i, "invalid literal")
		}
		*dst = false
		c.i = i + 5
		return nil
	default:
		return c.genericExpected[T]("boolean")
	}
}

// String decodes directly into any defined string type.
func (c *decoderCursor) String[T stringValue](dst *T) error {
	i := c.i
	if i < len(c.src) && c.src[i] == '"' {
		start := i + 1
		end, short := scanStringSpecialShort(c.src, start)
		if !short {
			end = scanStringSpecial(c.src, start)
		}
		if end < len(c.src) && c.src[end] == '"' && c.flags&(decoderZeroCopy|decoderSourceOwned) != 0 {
			*dst = T(byteview.String(c.src[start:end]))
			c.i = end + 1
			return nil
		}
	}
	return c.stringSlow(dst)
}

//go:noinline
func (c *decoderCursor) stringSlow[T stringValue](dst *T) error {
	if c.i < len(c.src) && c.src[c.i] == 'n' {
		if !literalNullAt(c.src, c.i) {
			return c.err(c.i, "invalid literal")
		}
		if c.flags&decoderReplace != 0 {
			*dst = ""
		}
		c.i += 4
		return nil
	}
	if c.i >= len(c.src) || c.src[c.i] != '"' {
		return c.genericExpected[T]("string")
	}
	start := c.i + 1
	end, short := scanStringSpecialShort(c.src, start)
	if !short {
		end = scanStringSpecial(c.src, start)
	}
	if end < len(c.src) && c.src[end] == '"' {
		c.ownSource()
		text := byteview.String(c.src[start:end])
		*dst = T(text)
		c.i = end + 1
		return nil
	}
	c.ownSource()
	c.ensureStringArena()
	p := c.slowParser()
	text, err := p.parseString()
	c.i = p.i
	c.adoptStringArena(p.strings)
	if err != nil {
		return err
	}
	*dst = T(text)
	return nil
}

// Number decodes a JSON number's original spelling into a defined string type.
func (c *decoderCursor) Number[T stringValue](dst *T) error {
	if c.i < len(c.src) && c.src[c.i] == 'n' {
		if !literalNullAt(c.src, c.i) {
			return c.err(c.i, "invalid literal")
		}
		if c.flags&decoderReplace != 0 {
			*dst = ""
		}
		c.i += 4
		return nil
	}
	if c.i < len(c.src) && c.src[c.i] == '"' {
		// encoding/json also accepts a JSON string whose unquoted contents
		// spell a valid JSON number; the string decode supplies the
		// ownership rules for the retained spelling.
		var content string
		if err := c.String(&content); err != nil {
			return err
		}
		if !ValidNumber(byteview.Bytes(content)) {
			return c.genericError[T](c.i, "string is not a valid number spelling")
		}
		*dst = T(content)
		return nil
	}
	start, end, err := c.numberToken[T]()
	if err != nil {
		return err
	}
	c.ownSource()
	text := byteview.String(c.src[start:end])
	*dst = T(text)
	c.i = end
	return nil
}

// Int decodes directly into any defined signed integer type.
func (c *decoderCursor) Int[T signedInteger](dst *T) error {
	n := len(c.src)
	if c.i < n && c.src[c.i] == 'n' {
		if !literalNullAt(c.src, c.i) {
			return c.err(c.i, "invalid literal")
		}
		if c.flags&decoderReplace != 0 {
			*dst = 0
		}
		c.i += 4
		return nil
	}
	start := c.i
	if start >= n {
		return c.genericExpected[T]("number")
	}
	base := unsafe.Pointer(unsafe.SliceData(c.src))
	i := start
	negative := false
	if fastByteAt(base, i) == '-' {
		negative = true
		i++
		if i == n {
			return c.err(start, "invalid number")
		}
	}
	if !isDigit(fastByteAt(base, i)) {
		return c.genericExpected[T]("number")
	}
	width := int(unsafe.Sizeof(*dst)) * 8
	limit := uint64(1) << (width - 1)
	if !negative {
		limit--
	}
	cutoff, cutlim := limit/10, limit%10
	value := uint64(0)
	if fastByteAt(base, i) == '0' {
		i++
		if i < n && isDigit(fastByteAt(base, i)) {
			return c.err(start, "invalid leading zero in number")
		}
	} else {
		if i+8 <= n {
			word := loadUint64LE(unsafe.Add(base, i))
			if invalid := nonDigitMask8(word); invalid != 0 {
				// One to seven digits ending at a proven non-digit: shift
				// the digits to the top of the word, backfill ASCII zeros,
				// and parse all of them at once. Values this short cannot
				// overflow destinations wider than sixteen bits, so the
				// range check folds away for them.
				k := bits.TrailingZeros64(invalid) / 8
				s := uint(8-k) * 8
				value = parse8DigitsWord(word<<s | digitLower>>(64-s))
				i += k
				if width <= 16 && value > limit {
					return c.genericError[T](start, "integer overflow")
				}
			} else if i+16 <= n && all16Digits(unsafe.Add(base, i)) {
				value = parse16Digits(unsafe.Add(base, i))
				i += 16
				if value > limit {
					return c.genericError[T](start, "integer overflow")
				}
			} else {
				value = parse8DigitsWord(word)
				i += 8
				if width <= 16 && value > limit {
					return c.genericError[T](start, "integer overflow")
				}
			}
		}
		for i < n && isDigit(fastByteAt(base, i)) {
			digit := uint64(fastByteAt(base, i) - '0')
			if value > cutoff || value == cutoff && digit > cutlim {
				return c.genericError[T](start, "integer overflow")
			}
			value = value*10 + digit
			i++
		}
	}
	if i < n && (fastByteAt(base, i) == '.' || fastByteAt(base, i) == 'e' || fastByteAt(base, i) == 'E') {
		if _, ok := scanNumberFast(base, len(c.src), start); !ok {
			_, message := scanNumber(c.src, start)
			return c.err(start, message)
		}
		return c.genericError[T](start, "fractional number cannot be stored in an integer")
	}
	if negative {
		*dst = T(-int64(value))
	} else {
		*dst = T(value)
	}
	c.i = i
	return nil
}

// Uint decodes directly into any defined unsigned integer type.
func (c *decoderCursor) Uint[T unsignedInteger](dst *T) error {
	n := len(c.src)
	if c.i < n && c.src[c.i] == 'n' {
		if !literalNullAt(c.src, c.i) {
			return c.err(c.i, "invalid literal")
		}
		if c.flags&decoderReplace != 0 {
			*dst = 0
		}
		c.i += 4
		return nil
	}
	start := c.i
	if start >= n {
		return c.genericExpected[T]("number")
	}
	base := unsafe.Pointer(unsafe.SliceData(c.src))
	if !isDigit(fastByteAt(base, start)) {
		return c.genericExpected[T]("number")
	}
	width := int(unsafe.Sizeof(*dst)) * 8
	limit := ^uint64(0)
	if width < 64 {
		limit = uint64(1)<<width - 1
	}
	cutoff, cutlim := limit/10, limit%10
	i := start
	value := uint64(0)
	if fastByteAt(base, i) == '0' {
		i++
		if i < n && isDigit(fastByteAt(base, i)) {
			return c.err(start, "invalid leading zero in number")
		}
	} else {
		if i+8 <= n {
			word := loadUint64LE(unsafe.Add(base, i))
			if invalid := nonDigitMask8(word); invalid != 0 {
				// See Int: parse a short digit run in one step.
				k := bits.TrailingZeros64(invalid) / 8
				s := uint(8-k) * 8
				value = parse8DigitsWord(word<<s | digitLower>>(64-s))
				i += k
				if width <= 16 && value > limit {
					return c.genericError[T](start, "unsigned integer overflow")
				}
			} else if i+16 <= n && all16Digits(unsafe.Add(base, i)) {
				value = parse16Digits(unsafe.Add(base, i))
				i += 16
				if value > limit {
					return c.genericError[T](start, "unsigned integer overflow")
				}
			} else {
				value = parse8DigitsWord(word)
				i += 8
				if width <= 16 && value > limit {
					return c.genericError[T](start, "unsigned integer overflow")
				}
			}
		}
		for i < n && isDigit(fastByteAt(base, i)) {
			digit := uint64(fastByteAt(base, i) - '0')
			if value > cutoff || value == cutoff && digit > cutlim {
				return c.genericError[T](start, "unsigned integer overflow")
			}
			value = value*10 + digit
			i++
		}
	}
	if i < n && (fastByteAt(base, i) == '.' || fastByteAt(base, i) == 'e' || fastByteAt(base, i) == 'E') {
		if _, ok := scanNumberFast(base, len(c.src), start); !ok {
			_, message := scanNumber(c.src, start)
			return c.err(start, message)
		}
		return c.genericError[T](start, "fractional number cannot be stored in an unsigned integer")
	}
	*dst = T(value)
	c.i = i
	return nil
}

// Float decodes directly into any defined float32 or float64 type.
func (c *decoderCursor) Float[T floatValue](dst *T) error {
	i := c.i
	if i < len(c.src) && (c.src[i] == '-' || isDigit(c.src[i])) {
		base := unsafe.Pointer(unsafe.SliceData(c.src))
		if value, end, ok := shortTypedFloatAt(base, len(c.src), i); ok {
			*dst = T(value)
			c.i = end
			return nil
		}
	}
	return c.floatSlow(dst)
}

//go:noinline
func (c *decoderCursor) floatSlow[T floatValue](dst *T) error {
	if c.i < len(c.src) && c.src[c.i] == 'n' {
		if !literalNullAt(c.src, c.i) {
			return c.err(c.i, "invalid literal")
		}
		if c.flags&decoderReplace != 0 {
			*dst = 0
		}
		c.i += 4
		return nil
	}
	if c.i >= len(c.src) || (c.src[c.i] != '-' && !isDigit(c.src[c.i])) {
		return c.genericExpected[T]("number")
	}
	start := c.i
	base := unsafe.Pointer(unsafe.SliceData(c.src))
	bits := int(unsafe.Sizeof(*dst)) * 8
	if bits == 64 {
		// scanTypedFloat64Number validates the digits and fast-paths the values
		// that convert with one exact multiply. Its end and ok drive validation
		// and cursor advance exactly as before, and on the inexact path it hands
		// back the mantissa and exponent it already recovered.
		end, value, exact, number, haveNumber, ok := scanTypedFloat64Number(base, len(c.src), start)
		if !ok {
			_, message := scanNumber(c.src, start)
			return c.err(start, message)
		}
		if !exact {
			// Outside the exact-multiply envelope, round with Eisel-Lemire from
			// the mantissa and exponent the scanner already recovered, and
			// reserve the scalar strconv path for the truncated or tie-ambiguous
			// inputs it defers on. Only wide mantissas re-scan for truncation
			// tracking.
			if !haveNumber {
				_, number, haveNumber = scanJSONNumber(base, len(c.src), start)
				haveNumber = haveNumber && !number.truncated
			}
			if haveNumber {
				if v, exactLemire := eiselLemire64(number.mantissa, number.exponent, number.negative); exactLemire {
					*dst = T(v)
					c.i = end
					return nil
				}
			}
			text := unsafe.String((*byte)(unsafe.Add(base, start)), end-start)
			var err error
			value, err = strconv.ParseFloat(text, 64)
			if err != nil {
				return c.genericError[T](start, "number out of range")
			}
		}
		*dst = T(value)
		c.i = end
		return nil
	}
	end, integer, negative, isInteger, ok := scanAnyNumberFast(base, len(c.src), start)
	if !ok {
		_, message := scanNumber(c.src, start)
		return c.err(start, message)
	}
	text := unsafe.String((*byte)(unsafe.Add(base, start)), end-start)
	var value float64
	var err error
	if isInteger && integer <= uint64(1)<<53 {
		value = float64(integer)
		if negative {
			value = -value
		}
	} else {
		value, err = strconv.ParseFloat(text, 32)
	}
	if err != nil {
		return c.genericError[T](start, "number out of range")
	}
	*dst = T(value)
	c.i = end
	return nil
}

func (c *decoderCursor) numberToken[T any]() (start, end int, err error) {
	if c.i >= len(c.src) || (c.src[c.i] != '-' && !isDigit(c.src[c.i])) {
		return c.i, c.i, c.genericExpected[T]("number")
	}
	start = c.i
	base := unsafe.Pointer(unsafe.SliceData(c.src))
	end, ok := scanNumberFast(base, len(c.src), start)
	if !ok {
		_, msg := scanNumber(c.src, start)
		return start, end, c.err(start, msg)
	}
	return start, end, nil
}

func (c *decoderCursor) genericExpected[T any](jsonType string) error {
	return c.genericError[T](c.i, "expected "+jsonType)
}

func (c *decoderCursor) genericError[T any](offset int, reason string) error {
	return &DecodeError{Offset: offset, Type: reflect.TypeFor[T](), Reason: reason}
}
