//go:build ignore

// Command float_eisel_table_gen writes float_eisel_table.go, the 128-bit
// powers of ten consumed by eiselLemire64. Run it with:
//
//	go run float_eisel_table_gen.go
//
// Entry p holds the 128-bit truncated significand of 10**p as {low64, high64}:
// the unique w with 2**127 <= w < 2**128 and w = floor(10**p * 2**t) for the t
// that makes w exactly 128 bits. eiselLemire64 recovers the matching binary
// exponent from floor(p*log2(10)); the significand here carries the digits.
//
// Provenance: GO-EISEL-001. This math/big generator is local. Its output is
// mathematically equivalent to the detailed-power table in Go 1.25.0 commit
// 6e676ab2b809d46623acb5988248d95d1eb7939c, src/strconv/eisel_lemire.go;
// see docs/provenance.md and LICENSE-GO.
package main

import (
	"bufio"
	"fmt"
	"log"
	"math/big"
	"os"
)

const (
	minExp = -348
	maxExp = 347
)

func main() {
	f, err := os.Create("float_eisel_table.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	defer func() {
		if err := w.Flush(); err != nil {
			log.Fatal(err)
		}
	}()

	fmt.Fprint(w, "// Code generated by float_eisel_table_gen.go; DO NOT EDIT.\n\n")
	fmt.Fprint(w, "package simdjson\n\n")
	fmt.Fprint(w, "// Provenance: GO-EISEL-001. Values are locally generated and equivalent to\n")
	fmt.Fprint(w, "// Go 1.25.0's detailed powers; see docs/provenance.md and LICENSE-GO.\n")
	fmt.Fprintf(w, "// detailedPowersOfTen holds, for each decimal exponent from %d to %d,\n", minExp, maxExp)
	fmt.Fprint(w, "// the 128-bit truncated significand of 10**exp10 as {low64, high64}. It\n")
	fmt.Fprint(w, "// feeds eiselLemire64, which converts a decimal mantissa and exponent to\n")
	fmt.Fprint(w, "// the nearest float64 with a pair of 64x64->128 multiplies. See Lemire,\n")
	fmt.Fprint(w, "// \"Number Parsing at a Gigabyte per Second\" (2021).\n")
	fmt.Fprintf(w, "const detailedPowersOfTenMinExp10 = %d\n", minExp)
	fmt.Fprintf(w, "const detailedPowersOfTenMaxExp10 = %d\n", maxExp)
	fmt.Fprint(w, "var detailedPowersOfTen = [...][2]uint64{\n")

	ten := big.NewInt(10)
	mask64 := new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 64), big.NewInt(1))
	for exp := minExp; exp <= maxExp; exp++ {
		num := big.NewInt(1)
		den := big.NewInt(1)
		if exp < 0 {
			den.Exp(ten, big.NewInt(int64(-exp)), nil)
		} else {
			num.Exp(ten, big.NewInt(int64(exp)), nil)
		}
		// scaled = floor(10**exp * 2**4096); 4096 bits of headroom covers the
		// whole magnitude range so the result always has at least 128 bits.
		scaled := new(big.Int).Lsh(num, 4096)
		scaled.Div(scaled, den)
		// Normalize to exactly 128 bits: floor(scaled / 2**(bitlen-128)).
		wv := new(big.Int).Rsh(scaled, uint(scaled.BitLen()-128))
		hi := new(big.Int).Rsh(wv, 64)
		lo := new(big.Int).And(wv, mask64)
		fmt.Fprintf(w, "\t{0x%016x, 0x%016x}, // 10^%d\n", lo, hi, exp)
	}
	fmt.Fprint(w, "}\n")
}
