// Command codegen owns simdjson's repository-local source generators.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"math/big"
	"os"
	"strings"
	"text/template"
)

func main() {
	if len(os.Args) != 2 {
		usage()
	}
	switch os.Args[1] {
	case "decoder-cursor":
		generateDecoderCursor()
	case "float-eisel-table":
		generateFloatEiselTable()
	case "typed-ops":
		generateTypedOps()
	default:
		usage()
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage: codegen {decoder-cursor|float-eisel-table|typed-ops}")
	os.Exit(2)
}

// decoder_cursor_gen renders the compiler-specific decoder cursor sources.
// It deliberately treats the Go source as preformatted text: stable Go cannot
// parse Go 1.27 generic methods, but it must still be able to reproduce every
// generated file byte-for-byte.
type generatedFile struct {
	Path     string
	Output   string
	BuildTag string
	Go127    bool
}

var generatedFiles = []generatedFile{
	{
		Path:     "decoder_cursor_pre_go127.go",
		Output:   "cursor",
		BuildTag: "!go1.27",
	},
	{
		Path:     "decoder_cursor_go127.go",
		Output:   "cursor",
		BuildTag: "go1.27",
		Go127:    true,
	},
	{
		Path:     "decoder_numeric_methods_pre_go127.go",
		Output:   "numeric",
		BuildTag: "!go1.27",
	},
	{
		Path:     "decoder_numeric_methods_go127.go",
		Output:   "numeric",
		BuildTag: "go1.27",
		Go127:    true,
	},
}

func generateDecoderCursor() {
	source, err := os.ReadFile("decoder_cursor.tmpl")
	if err != nil {
		decoderCursorFail(err)
	}
	// Control actions live on their own lines so the template remains easy to
	// read. Remove only those physical newlines before rendering; otherwise a
	// disabled branch would leave blank or indented lines in generated Go.
	source = compactControlLines(source)
	tmpl, err := template.New("decoder_cursor").Option("missingkey=error").Parse(string(source))
	if err != nil {
		decoderCursorFail(err)
	}

	type renderedFile struct {
		path string
		data []byte
	}
	rendered := make([]renderedFile, 0, len(generatedFiles))
	for _, file := range generatedFiles {
		var output bytes.Buffer
		if err := tmpl.Execute(&output, file); err != nil {
			decoderCursorFail(err)
		}
		rendered = append(rendered, renderedFile{path: file.Path, data: output.Bytes()})
	}

	for _, file := range rendered {
		current, err := os.ReadFile(file.path)
		if err == nil && bytes.Equal(current, file.data) {
			continue
		}
		if err != nil && !os.IsNotExist(err) {
			decoderCursorFail(err)
		}
		if err := os.WriteFile(file.path, file.data, 0o644); err != nil {
			decoderCursorFail(err)
		}
	}
}

func compactControlLines(source []byte) []byte {
	lines := strings.SplitAfter(string(source), "\n")
	var compact strings.Builder
	compact.Grow(len(source))
	for _, line := range lines {
		action := strings.TrimSpace(strings.TrimSuffix(line, "\n"))
		if strings.HasPrefix(action, "{{if ") ||
			strings.HasPrefix(action, "{{else") ||
			strings.HasPrefix(action, "{{end") {
			action = strings.ReplaceAll(action, " -}}", "}}")
			compact.WriteString(action)
			continue
		}
		compact.WriteString(line)
	}
	return []byte(compact.String())
}

func decoderCursorFail(err error) {
	fmt.Fprintln(os.Stderr, "decoder_cursor_gen:", err)
	os.Exit(1)
}

// float_eisel_table_gen writes internal/floatconv/eisel_table.go, the 128-bit
// powers of ten consumed by EiselLemire64. The generator runs from that package
// directory through its go:generate directive.
//
// Entry p holds the 128-bit truncated significand of 10**p as {low64, high64}:
// the unique w with 2**127 <= w < 2**128 and w = floor(10**p * 2**t) for the t
// that makes w exactly 128 bits. EiselLemire64 recovers the matching binary
// exponent from floor(p*log2(10)); the significand here carries the digits.
//
// Provenance: GO-EISEL-001. This math/big generator is local. Its output is
// mathematically equivalent to the detailed-power table in Go 1.25.0 commit
// 6e676ab2b809d46623acb5988248d95d1eb7939c, src/strconv/eisel_lemire.go;
// see docs/provenance.md and LICENSE-GO.
const (
	minExp = -348
	maxExp = 347
)

func generateFloatEiselTable() {
	f, err := os.Create("eisel_table.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	defer func() {
		if err := w.Flush(); err != nil {
			log.Fatal(err)
		}
	}()

	fmt.Fprint(w, "// Code generated by internal/cmd/codegen float-eisel-table; DO NOT EDIT.\n\n")
	fmt.Fprint(w, "package floatconv\n\n")
	fmt.Fprint(w, "// Provenance: GO-EISEL-001. Values are locally generated and equivalent to\n")
	fmt.Fprint(w, "// Go 1.25.0's detailed powers; see docs/provenance.md and LICENSE-GO.\n")
	fmt.Fprintf(w, "// detailedPowersOfTen holds, for each decimal exponent from %d to %d,\n", minExp, maxExp)
	fmt.Fprint(w, "// the 128-bit truncated significand of 10**exp10 as {low64, high64}. It\n")
	fmt.Fprint(w, "// feeds EiselLemire64, which converts a decimal mantissa and exponent to\n")
	fmt.Fprint(w, "// the nearest float64 with a pair of 64x64->128 multiplies. See Lemire,\n")
	fmt.Fprint(w, "// \"Number Parsing at a Gigabyte per Second\" (2021).\n")
	fmt.Fprintf(w, "const detailedPowersOfTenMinExp10 = %d\n", minExp)
	fmt.Fprintf(w, "const detailedPowersOfTenMaxExp10 = %d\n", maxExp)
	fmt.Fprint(w, "var detailedPowersOfTen = [...][2]uint64{\n")

	ten := big.NewInt(10)
	mask64 := new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 64), big.NewInt(1))
	for exp := minExp; exp <= maxExp; exp++ {
		num := big.NewInt(1)
		den := big.NewInt(1)
		if exp < 0 {
			den.Exp(ten, big.NewInt(int64(-exp)), nil)
		} else {
			num.Exp(ten, big.NewInt(int64(exp)), nil)
		}
		// scaled = floor(10**exp * 2**4096); 4096 bits of headroom covers the
		// whole magnitude range so the result always has at least 128 bits.
		scaled := new(big.Int).Lsh(num, 4096)
		scaled.Div(scaled, den)
		// Normalize to exactly 128 bits: floor(scaled / 2**(bitlen-128)).
		wv := new(big.Int).Rsh(scaled, uint(scaled.BitLen()-128))
		hi := new(big.Int).Rsh(wv, 64)
		lo := new(big.Int).And(wv, mask64)
		fmt.Fprintf(w, "\t{0x%016x, 0x%016x}, // 10^%d\n", lo, hi, exp)
	}
	fmt.Fprint(w, "}\n")
}

// typed_ops_gen generates the repeated typed-operation dispatch matrices.
type operation struct {
	name       string
	kind       string
	goType     string
	decode     bool
	encode     bool
	structural bool
}

var operations = []operation{
	{name: "Invalid", kind: "invalid"},
	{name: "Bool", kind: "bool", goType: "bool", decode: true, encode: true, structural: true},
	{name: "String", kind: "string", goType: "string", decode: true, encode: true, structural: true},
	{name: "Number", kind: "number", goType: "string", decode: true, encode: true},
	{name: "Int8", kind: "int", goType: "int8", decode: true, encode: true},
	{name: "Int16", kind: "int", goType: "int16", decode: true, encode: true},
	{name: "Int32", kind: "int", goType: "int32", decode: true, encode: true},
	{name: "Int64", kind: "int", goType: "int64", decode: true, encode: true, structural: true},
	{name: "Uint8", kind: "uint", goType: "uint8", decode: true, encode: true},
	{name: "Uint16", kind: "uint", goType: "uint16", decode: true, encode: true},
	{name: "Uint32", kind: "uint", goType: "uint32", decode: true, encode: true},
	{name: "Uint64", kind: "uint", goType: "uint64", decode: true, encode: true},
	{name: "Float32", kind: "float32", goType: "float32", decode: true, encode: true},
	{name: "Float64", kind: "float64", goType: "float64", decode: true, encode: true, structural: true},
	{name: "Struct", kind: "struct", decode: true, encode: true, structural: true},
	{name: "Slice", kind: "slice", decode: true, encode: true, structural: true},
	{name: "Array", kind: "array", decode: true, encode: true, structural: true},
	{name: "Pointer", kind: "pointer", decode: true},
	{name: "Map", kind: "map", decode: true, encode: true},
	{name: "Any", kind: "any", decode: true, encode: true},
	{name: "Bytes", kind: "bytes", decode: true},
	{name: "Quoted", kind: "quoted", decode: true, encode: true},
	{name: "Unmarshaler", kind: "unmarshaler", decode: true},
	{name: "Marshaler", kind: "marshaler", encode: true},
	{name: "Iface", kind: "iface", decode: true},
}

func generateTypedOps() {
	rewrites := []struct {
		path string
		name string
		body string
	}{
		{"typed_plan.go", "TYPED OP ENUM", renderEnum()},
		{"typed_compile.go", "TYPED STRUCTURAL FIELD ELIGIBILITY", renderStructuralEligibility()},
		{"typed_compiled_record.go", "TYPED CURSOR FIELD DISPATCH", renderDecode(false)},
		{"typed_compiled_record_structural.go", "TYPED STRUCTURAL FIELD DISPATCH", renderDecode(true)},
		{"encoder_execute_record.go", "TYPED ENCODER FIELD DISPATCH", renderEncodeField()},
		{"encoder_execute_record_specialized.go", "TYPED ENCODER VALUE DISPATCH", renderEncodeValue()},
	}
	for _, rewrite := range rewrites {
		if err := replaceGeneratedBlock(rewrite.path, rewrite.name, rewrite.body); err != nil {
			fmt.Fprintln(os.Stderr, "typed_ops_gen:", err)
			os.Exit(1)
		}
	}
}

func renderEnum() string {
	var out strings.Builder
	for i, op := range operations {
		fmt.Fprintf(&out, "\ttypedOp%s", op.name)
		if i == 0 {
			out.WriteString(" typedOp = iota")
		}
		out.WriteByte('\n')
	}
	return out.String()
}

func renderStructuralEligibility() string {
	var names []string
	for _, op := range operations {
		if op.structural {
			names = append(names, "typedOp"+op.name)
		}
	}
	return "\t\t\tcase " + strings.Join(names, ", ") + ":\n"
}

func renderDecode(structural bool) string {
	var out strings.Builder
	for _, op := range operations {
		if !op.decode {
			continue
		}
		fmt.Fprintf(&out, "\t\tcase typedOp%s:\n", op.name)
		for _, line := range decodeBody(op, structural) {
			fmt.Fprintf(&out, "\t\t\t%s\n", line)
		}
	}
	return out.String()
}

func decodeBody(op operation, structural bool) []string {
	switch op.kind {
	case "bool":
		return []string{"fieldErr = cursor.Bool((*bool)(fieldDst))"}
	case "string":
		if structural {
			return []string{"fieldErr = cursor.stringStructural((*string)(fieldDst))"}
		}
		return []string{"fieldErr = cursor.String((*string)(fieldDst))"}
	case "number":
		return []string{"fieldErr = cursor.Number((*string)(fieldDst))"}
	case "int":
		return []string{
			"if useStableNumericMethods {",
			fmt.Sprintf("\tfieldErr = cursor.%s((*%s)(fieldDst))", op.name, op.goType),
			"} else {",
			fmt.Sprintf("\tfieldErr = cursor.Int((*%s)(fieldDst))", op.goType),
			"}",
		}
	case "uint":
		return []string{
			"if useStableNumericMethods {",
			fmt.Sprintf("\tfieldErr = cursor.%s((*%s)(fieldDst))", op.name, op.goType),
			"} else {",
			fmt.Sprintf("\tfieldErr = cursor.Uint((*%s)(fieldDst))", op.goType),
			"}",
		}
	case "float32", "float64":
		return []string{
			"if useStableNumericMethods {",
			fmt.Sprintf("\tfieldErr = cursor.%s((*%s)(fieldDst))", op.name, op.goType),
			"} else {",
			fmt.Sprintf("\tfieldErr = cursor.Float((*%s)(fieldDst))", op.goType),
			"}",
		}
	case "struct":
		method := "decodeCompiledStruct"
		if structural {
			method += "Structural"
		}
		return []string{fmt.Sprintf("fieldErr = cursor.%s(fieldNode, fieldDst)", method)}
	case "slice":
		method := "decodeCompiledSlice"
		if structural {
			method += "Structural"
		}
		return []string{fmt.Sprintf("fieldErr = cursor.%s(fieldNode, fieldDst)", method)}
	case "array":
		method := "decodeCompiledArray"
		if structural {
			method += "Structural"
		}
		return []string{fmt.Sprintf("fieldErr = cursor.%s(fieldNode, fieldDst)", method)}
	case "pointer":
		return []string{"fieldErr = cursor.decodeCompiledPointer(fieldNode, fieldDst)"}
	case "map":
		return []string{"fieldErr = cursor.decodeCompiledMap(fieldNode, fieldDst)"}
	case "any":
		return []string{"fieldErr = cursor.decodeCompiledAny(fieldDst)"}
	case "bytes":
		return []string{"fieldErr = cursor.decodeCompiledBytes(fieldNode, fieldDst)"}
	case "quoted":
		return []string{"fieldErr = cursor.decodeQuotedField(fieldNode, fieldDst)"}
	case "unmarshaler":
		return []string{
			"switch fieldNode.kind {",
			"case typedUnmarshalerJSON:",
			"\tfieldErr = cursor.decodeViaUnmarshaler(fieldNode, fieldDst)",
			"case typedUnmarshalerSimd:",
			"\tfieldErr = cursor.decodeViaSimdHook(fieldNode, fieldDst)",
			"default:",
			"\tfieldErr = cursor.decodeViaTextUnmarshaler(fieldNode, fieldDst)",
			"}",
		}
	case "iface":
		return []string{"fieldErr = cursor.decodeCompiledIface(fieldNode, fieldDst)"}
	default:
		panic("missing decode body for " + op.name)
	}
}

func renderEncodeField() string {
	var out strings.Builder
	for _, op := range operations {
		if !op.encode {
			continue
		}
		fmt.Fprintf(&out, "\t\tcase typedOp%s:\n", op.name)
		for _, line := range encodeFieldBody(op) {
			fmt.Fprintf(&out, "\t\t\t%s\n", line)
		}
	}
	return out.String()
}

func encodeFieldBody(op operation) []string {
	switch op.kind {
	case "bool":
		return []string{
			"if *(*bool)(fieldSrc) {",
			"\te.dst = append(e.dst, \"true\"...)",
			"} else {",
			"\te.dst = append(e.dst, \"false\"...)",
			"}",
		}
	case "string":
		return []string{"e.dst = appendEncodedJSONString(e.dst, *(*string)(fieldSrc), e.escapeHTML)"}
	case "number":
		return []string{"err = e.encodeNumberLiteral(*(*string)(fieldSrc))"}
	case "int":
		expr := fmt.Sprintf("int64(*(*%s)(fieldSrc))", op.goType)
		if op.goType == "int64" {
			expr = "*(*int64)(fieldSrc)"
		}
		return []string{"e.dst = appendCompactInt(e.dst, " + expr + ")"}
	case "uint":
		expr := fmt.Sprintf("uint64(*(*%s)(fieldSrc))", op.goType)
		if op.goType == "uint64" {
			expr = "*(*uint64)(fieldSrc)"
		}
		return []string{"e.dst = appendCompactUint(e.dst, " + expr + ")"}
	case "float32":
		return []string{"err = e.encodeFloat(float64(*(*float32)(fieldSrc)), 32)"}
	case "float64":
		return []string{"err = e.encodeFloat(*(*float64)(fieldSrc), 64)"}
	case "struct", "slice", "array", "map":
		return []string{fmt.Sprintf("err = e.encode%s(encField.node, fieldSrc)", op.name)}
	case "any":
		return []string{"err = e.encodeAny(fieldSrc)"}
	case "quoted":
		return []string{"err = e.encodeQuoted(encField.node, fieldSrc)"}
	case "marshaler":
		return []string{"err = e.encodeMarshaler(encField.node, fieldSrc)"}
	default:
		panic("missing encode field body for " + op.name)
	}
}

func renderEncodeValue() string {
	var out strings.Builder
	for _, op := range operations {
		if !op.encode {
			continue
		}
		fmt.Fprintf(&out, "\tcase typedOp%s:\n", op.name)
		for _, line := range encodeValueBody(op) {
			fmt.Fprintf(&out, "\t\t%s\n", line)
		}
	}
	return out.String()
}

func encodeValueBody(op operation) []string {
	switch op.kind {
	case "bool":
		return []string{
			"if *(*bool)(src) {",
			"\te.dst = append(e.dst, \"true\"...)",
			"} else {",
			"\te.dst = append(e.dst, \"false\"...)",
			"}",
		}
	case "string":
		return []string{"e.dst = appendEncodedJSONString(e.dst, *(*string)(src), e.escapeHTML)"}
	case "number":
		return []string{"return e.encodeNumberLiteral(*(*string)(src))"}
	case "int":
		expr := fmt.Sprintf("int64(*(*%s)(src))", op.goType)
		if op.goType == "int64" {
			expr = "*(*int64)(src)"
		}
		return []string{"e.dst = appendCompactInt(e.dst, " + expr + ")"}
	case "uint":
		expr := fmt.Sprintf("uint64(*(*%s)(src))", op.goType)
		if op.goType == "uint64" {
			expr = "*(*uint64)(src)"
		}
		return []string{"e.dst = appendCompactUint(e.dst, " + expr + ")"}
	case "float32":
		return []string{"return e.encodeFloat(float64(*(*float32)(src)), 32)"}
	case "float64":
		return []string{"return e.encodeFloat(*(*float64)(src), 64)"}
	case "struct", "slice", "array", "map":
		return []string{fmt.Sprintf("return e.encode%s(field.node, src)", op.name)}
	case "any":
		return []string{"return e.encodeAny(src)"}
	case "quoted":
		return []string{"return e.encodeQuoted(field.node, src)"}
	case "marshaler":
		return []string{"return e.encodeMarshaler(field.node, src)"}
	default:
		panic("missing encode value body for " + op.name)
	}
}

func replaceGeneratedBlock(path, name, body string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	begin := []byte("// BEGIN GENERATED " + name)
	end := []byte("// END GENERATED " + name)
	if bytes.Count(data, begin) != 1 || bytes.Count(data, end) != 1 {
		return fmt.Errorf("%s: expected one %q block", path, name)
	}
	beginAt := bytes.Index(data, begin)
	bodyAt := bytes.IndexByte(data[beginAt:], '\n')
	if bodyAt < 0 {
		return fmt.Errorf("%s: unterminated begin marker for %q", path, name)
	}
	bodyAt += beginAt + 1
	endAt := bytes.Index(data[bodyAt:], end)
	if endAt < 0 {
		return fmt.Errorf("%s: missing end marker for %q", path, name)
	}
	endAt += bodyAt
	endLineAt := bytes.LastIndexByte(data[:endAt], '\n') + 1

	generated := make([]byte, 0, len(data)+len(body))
	generated = append(generated, data[:bodyAt]...)
	generated = append(generated, body...)
	generated = append(generated, data[endLineAt:]...)
	formatted, err := format.Source(generated)
	if err != nil {
		return fmt.Errorf("%s: format generated source: %w", path, err)
	}
	if bytes.Equal(data, formatted) {
		return nil
	}
	return os.WriteFile(path, formatted, 0o644)
}
